### ISSUE TITLE
Not possible to navigate when using internal redirect

### ISSUE THREAD

**Issue by netzarbeiter** [codefog/contao-mobile_menu#11]
The site structure looks like:
* main point (Internal redirect to link 1)
   - link 1
   - link 2
   - link 3

First click on "main point", "link 1", "link 2" and "link 3" show up.
Second click on "main point" the site of "link 1" opens.
Now the navigation "main point" is a **span** (Contao 3) or **strong** (Contao 4) and you can't navigate any more. Is this a bug or do you want us to change the behaviour in the template "nav_default"?

**Comment by qzminski** [comment]
What do you mean you can't navigate anymore? I have an identical situation like you on the below page (Praxis –> Philosophie) and the other navigation points are still usable.

http://www.didenta.de/de/philosophie.html

**Comment by netzarbeiter** [comment]
The structure:
![mobile_menu](https://cloud.githubusercontent.com/assets/1942550/22828120/e07cb902-ef9b-11e6-964d-38589978bb5f.png)

The gif:
https://www.netzarbeiter.ch/daten/mobile_menu.zip

**Comment by qzminski** [comment]
If the parent page is active it should initially show all the submenus inside it. Have you modified the CSS or the navigation template in any way that could potentially cause it?

**Comment by qzminski** [comment]
Fixed in 358da4a.
