### ISSUE TITLE
Feature: Keep .mod_mobile_menu in its place

### ISSUE THREAD

**Issue by Aybee** [codefog/contao-mobile_menu#12]
Hello Kamil,

thank you for your good work on this mobile menu.

Is it possible to add a new feature which keeps the module container in place? All you have to do is to make this line 
https://github.com/codefog/contao-mobile_menu/blob/master/assets/js/mobile-menu.jquery.js#L120
dependend on a new option 'keep_in_place'.

I need this because I like to use this menu on all viewport widths as the only one menu that is present. On large viewports it's much easier if it stays in its place where I included it. I then set it to position:relative. Position:fixed also works if it stays in it's place.

**Comment by qzminski** [comment]
Implemented in bf674df.

**Comment by Aybee** [comment]
😲 Thank you very much. Tested and it works. I wil use it immediately.
