### ISSUE TITLE
Trigger don't work with position:fixed;

### ISSUE THREAD

**Issue by DetlefT** [codefog/contao-mobile_menu#13]
Hi Kamil,

great extension! Thank you for this. It work's fine for me but there is an issue:

I find no solution to set the trigger to position:fixed; (or to position:sticky;). In both cases the trigger will scroll with the other content.
I insert the module at the end of my header after some div's. I set this css (no matter !important is set or not):
`.mobile_menu_trigger {
	position:fixed !important;
	top:30px;
}`
The trigger content:
`<span><i class="fa fa-bars">[nbsp]</i> Menü</span>`

If Mobile_menu ist activ, no other statement position:fixed; will work except your mod cookiebar.

 Best regards, Detlef

**Comment by qzminski** [comment]
That's very strange. Do you have that website online?

**Comment by DetlefT** [comment]
Have a look at [](http://www.test-69754.alfa3044.alfahosting-server.de/)

This is a test-account which will be down in ~ 1 week. I try to submit a new address to you if my client has decided for a provider.

**Comment by qzminski** [comment]
This is likely caused by the `transform` CSS rule applied to the wrapper element – see https://stackoverflow.com/a/15256339. I suggest that you disable the _off-canvas_ effect for that case and it should be back to normal. Couldn't find any other solution for that but I am open for the ideas.

**Comment by DetlefT** [comment]
Right solution! Back-to-top will work again and even position:fixed works fine.
Thank you for quick help!
