### ISSUE TITLE
collision with Mod Back-2-top

### ISSUE THREAD

**Issue by DetlefT** [codefog/contao-mobile_menu#14]
Hi Kamil,

in addition to issue #13 there will be a collision with Back-2-Top from [http://codyhouse.co/gem/back-to-top](url). If mobile_menu is activ, back-2-top doesn't work as usual. The button will stay at the bottom of the site.

Best regards, Detlef

**Comment by qzminski** [comment]
I believe that #13 would fix this one as well, so I will close it for now.
