### ISSUE TITLE
Not working with Contao 4.4.20

### ISSUE THREAD

**Issue by stateARTpb** [codefog/contao-mobile_menu#19]
It seems that this modue is not working with Contao  4.4.20

The mobile Navigation is opening but there is no "content". I added the navigation via Insert nothing, even simple text is not working. The Trigger is shown and works fine. (see Screenshot)

Any ideas? Thanks in advance!

<img width="446" alt="bildschirmfoto 2018-07-26 um 13 43 08" src="https://user-images.githubusercontent.com/22344664/43260480-e9602e6a-90d9-11e8-9d06-25ba7bc2fee8.png">

**Comment by qzminski** [comment]
Are you sure the DOM is empty and it's not because of the CSS?

Did you insert the module via insert tag? If so, can you insert it the regular way and see if the same issue occurs?

**Comment by Aybee** [comment]
Works in my Contao 4.4.20 with insert_module in the "Mobile menu" module.

Checkboxes:
Smartphone, Keep in place, Overlay, Animation.
