### ISSUE TITLE
TypeError: $("#mobile-menu-97").mobileMenu is not a function

### ISSUE THREAD

**Issue by kossi26** [codefog/contao-mobile_menu#21]
Hi codefog,
I use the release codefog/contao-mobile_menu 2.7.
I install the module and made the config how in the doc. But I get the following error (Uncaught TypeError: $("#mobile-menu-97").mobileMenu is not a function). 
Did you have a workaround.
Thank you

**Comment by Aybee** [comment]
You have to show a link to the page so we can see what's going wrong.

Either the script is not in your HTML markup or there's something wrong with the order of your script loading.

For this kind of questions best way is to ask in the forum for help first.
https://community.contao.org/de/
In the forums links menu you also can find EN, FR and PL forums.
