### ISSUE TITLE
Position in the source code

### ISSUE THREAD

**Issue by operatorone** [codefog/contao-mobile_menu#23]
Is there a way to change the position of the actual menu code in the source code? I would like to place it directly after the trigger code, so when using the tab key you can jump from the trigger in the menu.

At the moment the menu sits at the bottom of the page. So if you use the trigger you have to jump over all the links in between first to get to the menu items.

**Comment by qzminski** [comment]
This option is called `Keep menu in place`.

**Comment by operatorone** [comment]
Awesome. Thank you!!!
