### ISSUE TITLE
Contao 4.8.4 version a bug with articles / page assignment

### ISSUE THREAD

**Issue by redwise** [codefog/contao-mobile_menu#24]
hello, your extension causes a bug in the Contao 4.8.4 version for items associated with an individual rent.

1/1) ErrorCall to a member function query() on null
--
in tl_article.php line 70
at tl_article_mobile_page_layout_bundle->getActiveLayoutSections(object(DC_Table))in DC_Table.php line 4289
at DC_Table->parentView()in DC_Table.php line 360
at DC_Table->showAll()in Backend.php line 630
at Backend->getBackendModule('article', null)in BackendMain.php line 161
at BackendMain->run()in BackendController.php line 50
at BackendController->mainAction()in HttpKernel.php line 151
at HttpKernel->handleRaw(object(Request), 1)in HttpKernel.php line 68
at HttpKernel->handle(object(Request), 1, true)in Kernel.php line 198
at Kernel->handle(object(Request))in index.php line 31
at require('/home/staktffm/www.domain.de/update/web/index.php')in app.php line 4

**Comment by qzminski** [comment]
Are you sure it happens only if you have the `codefog/contao-mobile_menu` extension installed? The error message points to https://github.com/contao/mobile-page-layout-bundle which my module should not affect at all.

Also, what do you mean by "items associated with an individual rent"?

**Comment by redwise** [comment]
hello, I agree with you and I see it now.
The error only occurs when I play in your extension.
I created custom layout sections (slider) in the theme
If I click in the article with the assignment (slider) / edit the error message comes.

**Comment by qzminski** [comment]
And if you uninstall `codefog/contao-mobile_menu` and "click in the article with the assignment (slider)" the error message does **not** come up??

**Comment by redwise** [comment]
hello, I have to apologize. If I uninstall your extension the error message comes anyway.
It's up to the https://github.com/contao/mobile-page-layout-bundle extension.
You can close the ticket please.
Thank you for your help..
Steffen

**Comment by qzminski** [comment]
Please report the issue there. The fix should be fairly simple:

```diff
-$objLayout = $this->Database->query("SELECT sections FROM tl_layout WHERE sections!=''");
+$objLayout = \Database::getInstance()->query("SELECT sections FROM tl_layout WHERE sections!=''");
```

https://github.com/contao/mobile-page-layout-bundle/blob/master/src/Resources/contao/dca/tl_article.php#L70

**Comment by redwise** [comment]
Wow ... that was the problem!
Thank you so much!

**Comment by qzminski** [comment]
Glad it worked! Still, please open an issue at: https://github.com/contao/mobile-page-layout-bundle/issues so this problem can be solved once and for all.
