### ISSUE TITLE
Contao 4.13. and PHP 8.1

### ISSUE THREAD

**Issue by redwise** [codefog/contao-mobile_menu#26]
Hello, 

may I ask if you are updating your plugin to **Contao version 4.13**. and **PHP 8.1**?

**Comment by qzminski** [comment]
I have just pushed version 2.7.2 which should be compatible with these versions. Let me know if you encounter any problems.

**Comment by redwise** [comment]
Thank you very much for your very quick support.
Install works, I will test it later and give you feedback.

**Comment by redwise** [comment]
Thank you very much for the very fast support!!!
