### ISSUE TITLE
Question: Close menu when clicking anchor links

### ISSUE THREAD

**Issue by Webstylerin** [codefog/contao-mobile_menu#29]
I have an anchor link in the mobile navigation. What do I need to do to close the menu after clicking the anchor link? I know there is an option for one page sites, but I need it for one link only.

**Comment by Aybee** [comment]
Please ask this kind of question in the forum.

Besser direkt im Forum fragen. Dort bekommst du bestimmt sofort Hilfe. Für eine Spekulation sind es auch einfach etwas zu wenig Informationen. Die Dokumentation hier hast du ja bestimmt schon gelesen.

**Comment by Webstylerin** [comment]
Mach ich, danke. Issue bitte löschen.
