### ISSUE TITLE
Off canvas effect doesn't work

### ISSUE THREAD

**Issue by Webstylerin** [codefog/contao-mobile_menu#3]
Hi codefog.

I updated the mobile_menu to the new version 2.0.0 (Contao 3.5.3) and activated the option "Off canvas effect" (Position Right side) but I can scroll to the right side an see the menu even if not active.

Can you please take a look or give me a hint what I forgot? :)

Thx.
Nicole

**Comment by qzminski** [comment]
Do you have this website online so I can have a look? You also have to know that the mobile_menu off canvas by default only works with the ```#wrapper``` element.

**Comment by Webstylerin** [comment]
I will send you the link via email.

**Comment by qzminski** [comment]
Just for reference: a custom CSS code caused ```.mobile_menu``` element to have the ```absolute``` position. This is wrong as the element must have a ```fixed``` position (which is by default).
