### ISSUE TITLE
Possible conflict with jQuery SMINT

### ISSUE THREAD

**Issue by birdmedia** [codefog/contao-mobile_menu#7]
There seems to be a conflict with the jQuery SMINT plugin (http://www.outyear.co.uk/smint/). I'm not able to run these two scripts together in a project although I tried different "noConflict" setups. Any hints or ideas how to fix this problem?

**Comment by qzminski** [comment]
Do you get any errors in JS console?

**Comment by birdmedia** [comment]
No, the JS console doesn't return any errors. Maybe there is a conflict with some of the functions or variables. I was hoping you may have come accross a problem like this in combination with other scripts.

**Comment by qzminski** [comment]
I have never encountered any such problem yet. You need to debug this on your own I guess.

**Comment by qzminski** [comment]
Any news on this or can I close the task?

**Comment by birdmedia** [comment]
Unfortunately I couldn't solve the problem so far but I encountered a similar problem trying to combine your script with http://dimsemenov.com/plugins/royal-slider/ in another contao project.

**Comment by qzminski** [comment]
I'll leave this issue open then if anyone will have similar problem in the future.
